#!/usr/bin/env bash
set -e
set -u
set -o pipefail
IFS=$'\n\t'

# Francisco Diéguez Souto (frandieguez@ubuntu.com)
# This script is licensed under MIT License.
#
# This program just modifies the value of backlight keyboard for Apple Laptops
# You must run it as root user or via sudo.
# As a shortcut you could allow to admin users to run via sudo without password
# prompt. To do this you must add sudoers file the next contents:
#
#  Cmnd_Alias CMDS = /usr/local/bin/keyboard-backlight
#  %admin ALL = (ALL) NOPASSWD: CMDS
#
# After this you can use this script as follows:
#
#     Increase backlight keyboard:
#	    $ sudo keyboard-backlight up
#     Decrease backlight keyboard:
#	    $ sudo keyboard-backlight down
#     Increase to total value backlight keyboard:
#	    $ sudo keyboard-backlight total
#     Turn off backlight keyboard:
#	    $ sudo keyboard-backlight off
#
# You can customize the amount of backlight by step by changing the INCREMENT
# variable as you want it.

backlight=$(cat /sys/class/leds/smc::kbd_backlight/brightness)
increment=15
set_value=0

check_is_sudo() {
    if [[ $EUID -ne 0 ]]; then
        printf '\033[31mRequires root privileges. Use sudo.\033[0m\n' >&2
        exit 1
    fi
}

main() {
    check_is_sudo

    case $1 in

        up)
            total=`expr "${backlight}" + "${increment}"`
            if [[ "${total}" -gt "255" ]]; then
                exit 1
            fi
            set_value=1
            ;;
        down)
            total=`expr ${backlight} - "${increment}"`
            if [[ "${total}" -lt "0" ]]; then
                exit 1
            fi
            set_value=1
            ;;
        total)
	        temp_value="${backlight}"
	        while [[ "${temp_value}" -lt "255" ]]; do
		        temp_value=`expr "${temp_value}" + 1`
		        if [[ "${temp_value}" -gt "255" ]]; then temp_value=255; fi
		        printf  '%s\n' "${temp_value}" > /sys/class/leds/smc::kbd_backlight/brightness
	        done
            ;;
        off)
	        temp_value="${backlight}"
	        while [[ "${temp_value}" -gt "0" ]]; do
		        temp_value=`expr "${temp_value}" - 1`
		        if [ "${temp_value}" -lt "0" ]; then temp_value=0; fi
		        printf  '%s\n' "${temp_value}" > /sys/class/leds/smc::kbd_backlight/brightness
	        done
            ;;
        *)
            printf 'Use: keyboard-backlight up|down|total|off\n'
            ;;
    esac

    if [[ "${set_value}" -eq "1" ]]; then
        printf '%s' "${total}" > /sys/class/leds/smc::kbd_backlight/brightness
    fi
}

main "$@"
