#!/usr/bin/env bash
set -e
set -u
set -o pipefail
IFS=$'\n\t'

check_is_sudo() {
    if (( EUID != 0 )); then
        msg_error "Requires root privileges. Use sudo."
        exit 1
    fi
}

open_and_mount() {
    sudo cryptsetup luksOpen ~/.password-store/password-store.luks.con pass \
        && sudo mount /dev/mapper/pass ~/.password-store \
        && printf "\nSuccessfully opened and mounted!\nNow use 'pass'\n\n"
}

umount_and_close() {
    sudo umount ~/.password-store \
        && sudo cryptsetup luksClose /dev/mapper/pass \
        && printf "\nSuccessfully unmounted and closed!\n\n"
}

main() {
    check_is_sudo

    PS3='Please enter your choice: '
    options=("open and mount container" "umount and close container")
    select opt in "${options[@]}"; do
        case $opt in
            "open and mount container")
                open_and_mount
                exit
                ;;
            "umount and close container")
                umount_and_close
                exit
                ;;
            *)
                printf "Invalid option.\n"
                ;;
        esac
    done
}

main
