#!/usr/bin/env bash
set -e
set -u
set -o pipefail
IFS=$'\n\t'

msg_info() {
    printf '\033[33m%s\033[0m\n' "$1"
}

msg_error() {
    printf '\033[91m%s\033[0m\n' "$1" >&2
}

initial_check() {
    if (( EUID != 0 )); then
        msg_error "This program requires root privileges. Use sudo."
        exit 1
    fi

    if [[ "$(uname)" == "Darwin" ]]; then
        msg_error "You are not running macOS, exiting."
        exit 1
    fi
}

device_selection() {
    local devices
    devices=$(diskutil list)
    msg_info "List of available devices:"
    printf '%s\n' "${devices}"
    read -r -p "Type in the TOP disk identifier to modify (example: disk1 / disk2 / etc.): " device
}

scheme_selection() {
    printf '\n'
    PS3="Choose your partition scheme: "
    select opt in MBR GPT; do
        case $opt in
            MBR)
                scheme=mbr
                break
                ;;
            GPT)
                scheme=gpt
                break
                ;;
            *)
                printf 'Invalid option %s\n' "${REPLY}"
                ;;
        esac
    done
}

filetype_selection() {
    printf '\n'
    PS3="Choose your file system type: "
    select opt in FAT32 exFAT APFS APFS-Encrypted JHFS+ HFS+; do
        case $opt in
            FAT32)
                filesystem=FAT32
                break
                ;;
            exFAT)
                filesystem=exFAT
                break
                ;;
            APFS)
                filesystem=APFS
                break
                ;;
            APFS-Encrypted)
                filesystem=APFS
                encryption=enabled
                break
                ;;
            JHFS+)
                filesystem=JHFS+
                break
                ;;
            HFS+)
                filesystem=HFS+
                break
                ;;
            *)
                printf 'Invalid option %s\n' "${REPLY}"
                ;;
        esac
    done

    if [ -z "${encryption:-}" ]; then
        encryption=none
    fi
}

name_selection() {
    printf '\n'
    while true; do
        read -r -p "Enter device new name (max 11 chars): " label
        label="${label#"${label%%[![:space:]]*}"}"
        label="${label%"${label##*[![:space:]]}"}"
        label="${label^^}"

        if [[ -z "${label}" ]]; then
            printf 'Name cannot be empty.\n'
            continue
        fi

        if [[ ! "${label}" =~ ^[A-Za-z0-9-]+$ ]]; then
            printf 'Invalid characters. Use only letters, numbers, or -.\n'
            continue
        fi

        if  (( ${#label} <= 11 )); then
            break
        else
            printf 'Too long (%s chars). Try again.\n' "${#label}"
        fi
    done
}

final_warning() {
    printf '\n'
    msg_info "  ============= "
    msg_info "  LAST REMINDER "
    msg_info "  ============= "
    msg_info "  Selected drive: /dev/${device}"
    msg_info "  Partition scheme: ${scheme^^}"
    msg_info "  File system: ${filesystem}"
    msg_info "  Encryption: ${encryption}"
    msg_info "  Name: ${label}"
    printf '\n'

    while true; do
        read -r -p "Are you sure you want to continue? [Y/n] " response
        response=${response:-Y}
        case "$response" in
            [Yy]|[Yy][Ee][Ss])
                return 0
                ;;
            [Nn]|[Nn][Oo])
                return 1
                ;;
            *)
                msg_error "Please enter yes or no."
                ;;
        esac
    done
}

sanitize() {
    msg_info "Unmounting drive..."
    # return true to avoid exiting when the device is not mounted
    diskutil unmountDisk /dev/"${device}" || :
    sync
    sleep 5

    msg_info "Wiping all signatures and partition tables..."
    gpt destroy /dev/"${device}"
    sleep 5
    diskutil eraseDisk FREE none /dev/"${device}"
    sleep 5
}

formatting() {
    msg_info "Creating ${scheme^^} partition scheme and filesystem..."
    diskutil eraseDisk "${filesystem}" "${label}" "${scheme}" /dev/"${device}"
    sleep 5

    if [ "${opt}" = "APFS-Encrypted" ]; then
        msg_info "Beginning encryption..."
        disk_id=$(diskutil info "${label}" | grep "Device Identifier" | awk '{print $NF}')
        diskutil apfs encryptVolume "${disk_id}" -user disk
    fi

    msg_info "Operation finished."
}

main() {
    initial_check
    device_selection
    scheme_selection
    filetype_selection
    name_selection
    final_warning && {
        sanitize
        formatting
    }
}

main
