#!/usr/bin/env bash
set -e
set -u
set -o pipefail
IFS=$'\n\t'

check_is_sudo() {
    if (( EUID != 0 )); then
        printf '\033[31mRequires root privileges. Use sudo.\033[0m\n' >&2
        exit 1
    fi
}

spin() {
    local sp
    sp='/-\|'
    printf ' '
    while sleep 0.1; do
        printf '\b%.1s' "$sp"
        sp=${sp#?}${sp%???}
    done
}

wpasupplicant_method() {
    local spinpid
    wpa_cli scan
    printf 'Waiting 20 seconds before showing results...\n'
    spin &
    spinpid=$!
    sleep 20
    kill "${spinpid}"
    printf '\n'
    wpa_cli scan_results
}

aircrackng_method() {
    local interface
    interface=$(ip route get 1.1.1.1 | grep -oP 'dev\s+\K[^ ]+')
    airmon-ng start "${interface}"
    airodump-ng "${interface}mon"
    airmon-ng stop "${interface}mon"
}

main() {
    check_is_sudo

    while true; do
        printf 'Choose which method to use:\n'
        printf '  [1] wpa_supplicant\n'
        printf '  [2] Aircrack-ng\n'
        read -r -p "Selected method => " choice
        printf '\n'

        case "$choice" in
            1)
                wpasupplicant_method
                break
                ;;
            2)
                aircrackng_method
                break
                ;;
            *)
                printf 'Wront input, please choose either 1 or 2.\n\n'
                ;;
        esac
    done
}

main
